In [3]:
import nashpy as nash

In [2]:
import numpy as np

In [4]:
A = [[3, 1], [0, 2]]
B = [[2, 1], [0, 3]]
battle_of_the_sexes = nash.Game(A, B)

In [5]:
battle_of_the_sexes

Bi matrix game with payoff matrices:

Row player:
[[3 1]
 [0 2]]

Column player:
[[2 1]
 [0 3]]

In [6]:
A = [[1, -1], [-1, 1]]
B = [[-1, 1], [1, -1]]
mathing_pennies = nash.Game(A, B)

In [7]:
mathing_pennies

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

In [8]:
A = [[1, -1], [-1, 1]]
matching_pennies = nash.Game(A)
matching_pennies

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

In [14]:
#probablity distribution of players

sigma_r = np.array([.8, .2])
sigma_c = np.array([.6, .4])

In [11]:
matching_pennies[sigma_r, sigma_c]

array([ 0.12, -0.12])

In [12]:
sigma_r = np.array([1, 0])
sigma_c = np.array([.9, .1])

In [13]:
matching_pennies[sigma_c, sigma_r]

array([ 0.8, -0.8])

In [15]:
A = np.array([[1, 1, -1], [2, -1, 0]])
B = np.array([[1/2, -1, -1/2], [-1, 3, 2]])
game = nash.Game(A, B)
game

Bi matrix game with payoff matrices:

Row player:
[[ 1  1 -1]
 [ 2 -1  0]]

Column player:
[[ 0.5 -1.  -0.5]
 [-1.   3.   2. ]]

In [25]:
eqs = game.support_enumeration()

In [23]:
#only after enumeration, since eqs is a generator
for eq in eqs:
    print(eq)

(array([0.66666667, 0.33333333]), array([-0.        ,  0.33333333,  0.66666667]))


In [26]:
#only after enumeration, since eqs is a generator
list(eqs)

[(array([0.66666667, 0.33333333]),
  array([-0.        ,  0.33333333,  0.66666667]))]

In [27]:
eqs = game.vertex_enumeration()
list(eqs)

[(array([0.66666667, 0.33333333]),
  array([-1.85037171e-17,  3.33333333e-01,  6.66666667e-01]))]

In [28]:
A = [[3, 1], [0, 2]]
B = [[2, 1], [0, 3]]
battle_of_the_sexes = nash.Game(A, B)

In [29]:
battle_of_the_sexes


Bi matrix game with payoff matrices:

Row player:
[[3 1]
 [0 2]]

Column player:
[[2 1]
 [0 3]]

In [31]:
battle_of_the_sexes.lemke_howson(initial_dropped_label=0)

(array([1., 0.]), array([1., 0.]))

In [32]:
for label in range(4):
    print(battle_of_the_sexes.lemke_howson(initial_dropped_label=label))

(array([1., 0.]), array([1., 0.]))
(array([0., 1.]), array([0., 1.]))
(array([1., 0.]), array([1., 0.]))
(array([0., 1.]), array([0., 1.]))


In [33]:
eqs = battle_of_the_sexes.lemke_howson_enumeration()

In [34]:
list(eqs)

[(array([1., 0.]), array([1., 0.])),
 (array([0., 1.]), array([0., 1.])),
 (array([1., 0.]), array([1., 0.])),
 (array([0., 1.]), array([0., 1.]))]

In [35]:
for eq in battle_of_the_sexes.support_enumeration():
    print(eq)

(array([1., 0.]), array([1., 0.]))
(array([0., 1.]), array([0., 1.]))
(array([0.75, 0.25]), array([0.25, 0.75]))
