In [3]:
import nashpy as nash

In [2]:
import numpy as np

In [4]:
A = [[3, 1], [0, 2]]
B = [[2, 1], [0, 3]]
battle_of_the_sexes = nash.Game(A, B)

In [5]:
battle_of_the_sexes

Bi matrix game with payoff matrices:

Row player:
[[3 1]
 [0 2]]

Column player:
[[2 1]
 [0 3]]

In [6]:
A = [[1, -1], [-1, 1]]
B = [[-1, 1], [1, -1]]
mathing_pennies = nash.Game(A, B)

In [7]:
mathing_pennies

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

In [8]:
A = [[1, -1], [-1, 1]]
matching_pennies = nash.Game(A)
matching_pennies

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

In [14]:
#probablity distribution of players

sigma_r = np.array([.8, .2])
sigma_c = np.array([.6, .4])

In [11]:
matching_pennies[sigma_r, sigma_c]

array([ 0.12, -0.12])

In [12]:
sigma_r = np.array([1, 0])
sigma_c = np.array([.9, .1])

In [13]:
matching_pennies[sigma_c, sigma_r]

array([ 0.8, -0.8])