In [1]:
import nashpy as nash

In [10]:
import numpy as np

In [4]:
A = [[3, 1], [0, 2]]
B = [[2, 1], [0, 3]]
battle_of_the_sexes = nash.Game(A, B)

In [5]:
battle_of_the_sexes

Bi matrix game with payoff matrices:

Row player:
[[3 1]
 [0 2]]

Column player:
[[2 1]
 [0 3]]

In [8]:
A = [[1, -1], [-1, 1]]
B = [[-1, 1], [1, -1]]
mathing_pennies = nash.Game(A, B)

In [9]:
mathing_pennies

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]