In [2]:
import nashpy as nash

In [3]:
import numpy as np

In [4]:
A = [[3, 1], [0, 2]]
B = [[2, 1], [0, 3]]
battle_of_the_sexes = nash.Game(A, B)

In [5]:
battle_of_the_sexes

Bi matrix game with payoff matrices:

Row player:
[[3 1]
 [0 2]]

Column player:
[[2 1]
 [0 3]]

In [6]:
A = [[1, -1], [-1, 1]]
B = [[-1, 1], [1, -1]]
mathing_pennies = nash.Game(A, B)

In [7]:
mathing_pennies

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

In [8]:
A = [[1, -1], [-1, 1]]
matching_pennies = nash.Game(A)
matching_pennies

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

In [9]:
#probablity distribution of players

sigma_r = np.array([.8, .2])
sigma_c = np.array([.6, .4])

In [10]:
matching_pennies[sigma_r, sigma_c]

array([ 0.12, -0.12])

In [11]:
sigma_r = np.array([1, 0])
sigma_c = np.array([.9, .1])

In [12]:
matching_pennies[sigma_c, sigma_r]

array([ 0.8, -0.8])

In [60]:
#Colonel Blotto zero-sum game (this game has no saddle point)

A = [[4, 2, 1, 0], [1, 3, 0, -1], [-2, 2, 2, -2], [-1, 0, 3, 1], [0, 1, 2, 4]]
Colonel_Blotto = nash.Game(A)

#payoff in mixed Strategies

x = np.array([.7, 0, 0, 0, .3])
y = np.array([.1, .9, 0, 0])

# x(Ay) = (xA)y is the payoff

Colonel_Blotto[x, y]

#Any matrix game has a saddle point in mixed strategies


array([ 1.81, -1.81])

In [47]:
eqs = Colonel_Blotto.support_enumeration()
list(eqs)

C:\Users\Mohammad.FT\anaconda3\lib\site-packages\nashpy\algorithms\support_enumeration.py:196: RuntimeWarning: 
An even number of (0) equilibria was returned. This
indicates that the game is degenerate. Consider using another algorithm
to investigate.
                  
  warnings.warn(warning, RuntimeWarning)


[]

In [48]:
eqs = Colonel_Blotto.vertex_enumeration()
list(eqs)

[(array([ 4.44444444e-01,  0.00000000e+00,  1.11111111e-01, -1.69617407e-17,
          4.44444444e-01]),
  array([0.03333333, 0.53333333, 0.35555556, 0.07777778])),
 (array([ 4.44444444e-01,  0.00000000e+00,  1.11111111e-01, -1.69617407e-17,
          4.44444444e-01]),
  array([0.07777778, 0.35555556, 0.53333333, 0.03333333]))]

In [51]:
eqs = Colonel_Blotto.fictitious_play(iterations=5)
list(eqs)

[[array([0, 0, 0, 0, 0]), array([0, 0, 0, 0])],
 [array([0., 1., 0., 0., 0.]), array([0., 0., 1., 0.])],
 [array([0., 1., 0., 1., 0.]), array([0., 0., 1., 1.])],
 [array([0., 1., 0., 1., 1.]), array([1., 0., 1., 1.])],
 [array([0., 1., 0., 1., 2.]), array([2., 0., 1., 1.])],
 [array([1., 1., 0., 1., 2.]), array([3., 0., 1., 1.])]]

In [45]:
eqs = Colonel_Blotto.lemke_howson_enumeration()
list(eqs)

[(array([0.44444444, 0.        , 0.11111111, 0.        , 0.44444444]),
  array([0.07777778, 0.35555556, 0.53333333, 0.03333333])),
 (array([0.44444444, 0.        , 0.11111111, 0.        , 0.44444444]),
  array([0.03333333, 0.53333333, 0.35555556, 0.07777778])),
 (array([0.44444444, 0.        , 0.11111111, 0.        , 0.44444444]),
  array([0.03333333, 0.53333333, 0.35555556, 0.07777778])),
 (array([0.44444444, 0.        , 0.11111111, 0.        , 0.44444444]),
  array([0.03333333, 0.53333333, 0.35555556, 0.07777778])),
 (array([0.44444444, 0.        , 0.11111111, 0.        , 0.44444444]),
  array([0.07777778, 0.35555556, 0.53333333, 0.03333333])),
 (array([0.44444444, 0.        , 0.11111111, 0.        , 0.44444444]),
  array([0.07777778, 0.35555556, 0.53333333, 0.03333333])),
 (array([0.44444444, 0.        , 0.11111111, 0.        , 0.44444444]),
  array([0.03333333, 0.53333333, 0.35555556, 0.07777778])),
 (array([0.44444444, 0.        , 0.11111111, 0.        , 0.44444444]),
  array([0.0

In [59]:
#payoff in mixed Strategies

x = np.array([.7, 0, 0, 0, .3])
y = np.array([.1, .9, 0, 0])

Colonel_Blotto[x, y]

array([ 1.81, -1.81])

In [13]:
A = np.array([[1, 1, -1], [2, -1, 0]])
B = np.array([[1/2, -1, -1/2], [-1, 3, 2]])
game = nash.Game(A, B)
game

Bi matrix game with payoff matrices:

Row player:
[[ 1  1 -1]
 [ 2 -1  0]]

Column player:
[[ 0.5 -1.  -0.5]
 [-1.   3.   2. ]]

In [16]:
eqs = game.support_enumeration()

In [15]:
#only after enumeration, since eqs is a generator
for eq in eqs:
    print(eq)

(array([0.66666667, 0.33333333]), array([-0.        ,  0.33333333,  0.66666667]))


In [17]:
#only after enumeration, since eqs is a generator
list(eqs)

[(array([0.66666667, 0.33333333]),
  array([-0.        ,  0.33333333,  0.66666667]))]

In [18]:
eqs = game.vertex_enumeration()
list(eqs)

[(array([0.66666667, 0.33333333]),
  array([-1.85037171e-17,  3.33333333e-01,  6.66666667e-01]))]

In [19]:
A = [[3, 1], [0, 2]]
B = [[2, 1], [0, 3]]
battle_of_the_sexes = nash.Game(A, B)

In [20]:
battle_of_the_sexes

Bi matrix game with payoff matrices:

Row player:
[[3 1]
 [0 2]]

Column player:
[[2 1]
 [0 3]]

In [21]:
battle_of_the_sexes.lemke_howson(initial_dropped_label=0)

(array([1., 0.]), array([1., 0.]))

In [22]:
for label in range(4):
    print(battle_of_the_sexes.lemke_howson(initial_dropped_label=label))

(array([1., 0.]), array([1., 0.]))
(array([0., 1.]), array([0., 1.]))
(array([1., 0.]), array([1., 0.]))
(array([0., 1.]), array([0., 1.]))


In [23]:
eqs = battle_of_the_sexes.lemke_howson_enumeration()

In [24]:
list(eqs)

[(array([1., 0.]), array([1., 0.])),
 (array([0., 1.]), array([0., 1.])),
 (array([1., 0.]), array([1., 0.])),
 (array([0., 1.]), array([0., 1.]))]

In [25]:
for eq in battle_of_the_sexes.support_enumeration():
    print(eq)

(array([1., 0.]), array([1., 0.]))
(array([0., 1.]), array([0., 1.]))
(array([0.75, 0.25]), array([0.25, 0.75]))


In [26]:
#Repeated games
#pip install axelrod, study prisoner's dilemma

In [27]:
import axelrod as axl

In [28]:
player1 = axl.TitForTat()
player2 = axl.Alternator()
match = axl.Match((player1, player2), turns=6)
match.play()

[(C, C), (C, D), (D, C), (C, D), (D, C), (C, D)]